// packages/front-end/src/components/App.tsx
import React, { useEffect } from 'react';
import GeneticDriftWorld from '../../../packages/sim-engine/worlds/GeneticDriftWorld';
import BaseLoop from '../../../packages/sim-engine/loops/BaseLoop';
import HungryAgent from '../../../packages/sim-engine/agents/HungryAgent';

const App = (props) => {
  useEffect(() => {
    let world = new GeneticDriftWorld({ x: 25, y: 25, foodPerCycle: 200 });
    let loop = new BaseLoop({ fireEvents: true, tickFunc: requestAnimationFrame, world: world });
    let generations = 0;
    console.log = document.getElementById('renderer-output').append;
    loop.addEventListener('cycle', (entities) => {
      let agents: HungryAgent[] = entities.filter((e) => e instanceof BaseAgent) as HungryAgent[];
      generations++;
      console.log(`Gen ${generations}`);
      console.log(agents.length);
      let totalSpeed = 0;
      let totalSense = 0;
      for (const a of agents) {
        totalSpeed += a.speed;
        totalSense += a.detectionRange;
      }
      console.log('Avg Speed: ', totalSpeed / agents.length);
      console.log('Avg Detection Range: ', totalSense / agents.length);
    });
  }, []);
  return (
    <div>
      Hello, World!
      <div id="renderer-output"></div>
    </div>
  );
};

export default App;

// packages/svelte-frontend/src/App.svelte
<script lang="ts">
  import { BaseLoop, GeneticDriftWorld, BaseAgent, HungryAgent, PixiRenderer } from '@simulation-engine';
  import { onMount } from 'svelte';
  let world = new GeneticDriftWorld({x: 20, y: 20, foodPerCycle: 35});
  let renderer = new PixiRenderer();
  renderer.addSprites([{className: 'Food', url: 'static/strawberry.png'}, {className: 'HungryAgent', url: 'static/bat.png'}]);
  onMount(() => {
    document.getElementById('2drender').appendChild(renderer.app.view);
    loop.start();
  })
  let loop = new BaseLoop({ fireEvents: true, tickFunc: (f) => window.requestAnimationFrame(f), world, renderer});
  let generations = 0;
  let avgSpeed = 0;
  let avgSense = 0;
  let countAgents = 0;
  loop.addEventListener('cycle', (entities) => {
    let agents: HungryAgent[] = entities.filter((e) => e instanceof BaseAgent) as HungryAgent[];
    generations++;
    let totalSpeed = 0;
    let totalSense = 0;
    for(const a of agents) {
      totalSpeed += a.speed;
      totalSense += a.detectionRange;
    }
    countAgents = agents.length;
    avgSense = totalSense / countAgents;
    avgSpeed = totalSpeed / countAgents;
  })
  let name = 'wold';


</script>

<main>
  <h1>Hello {name}</h1>
  Generation {generations}: {countAgents} organisms<br />
  Avg Speed: {avgSpeed} <br />
  Avg Sense: {avgSense} <br />
  <div id='2drender'></div>
</main>
